(.venv) praveen@golu:~/bug_hunting/bugboss$ python3 main.py --modules proto_pollution
[!] Selenium not available. DOM-based tests will be skipped.
[+] Testing: https://edge.vbd.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155670>: Failed to resolve 'edge.vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vbd.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155a30>: Failed to resolve 'edge.vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vbd.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155cd0>: Failed to resolve 'edge.vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://api.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='api.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156060>: Failed to resolve 'api.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://api.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='api.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156750>: Failed to resolve 'api.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://api.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='api.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981569f0>: Failed to resolve 'api.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://atlantis.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='atlantis.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156cc0>: Failed to resolve 'atlantis.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='atlantis.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156390>: Failed to resolve 'atlantis.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='atlantis.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981563c0>: Failed to resolve 'atlantis.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://csp.infra.l.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='csp.infra.l.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155cd0>: Failed to resolve 'csp.infra.l.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.infra.l.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='csp.infra.l.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981554f0>: Failed to resolve 'csp.infra.l.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.infra.l.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='csp.infra.l.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156ea0>: Failed to resolve 'csp.infra.l.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://border.qa.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='border.qa.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157590>: Failed to resolve 'border.qa.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.qa.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='border.qa.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b60>: Failed to resolve 'border.qa.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.qa.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='border.qa.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157fe0>: Failed to resolve 'border.qa.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-cad.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-cad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598397620>: Failed to resolve 'activation-cad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cad.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-cad.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b60>: Failed to resolve 'activation-cad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cad.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-cad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981573b0>: Failed to resolve 'activation-cad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://grafana.fuze-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='grafana.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155940>, 'Connection to grafana.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://grafana.fuze-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='grafana.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598154e60>, 'Connection to grafana.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://grafana.fuze-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='grafana.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155760>, 'Connection to grafana.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://atlantis.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156a20>: Failed to resolve 'atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156a50>: Failed to resolve 'atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156cc0>: Failed to resolve 'atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-sgp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138bc0>: Failed to resolve 'activation-sgp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-sgp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156690>: Failed to resolve 'activation-sgp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-sgp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156c00>: Failed to resolve 'activation-sgp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.ukp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981562d0>: Failed to resolve 'edge.ukp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.ukp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155460>: Failed to resolve 'edge.ukp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.ukp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156210>: Failed to resolve 'edge.ukp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://concourse-test.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='concourse-test.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157f20>: Failed to resolve 'concourse-test.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://concourse-test.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='concourse-test.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157d10>: Failed to resolve 'concourse-test.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://concourse-test.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='concourse-test.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5983d51c0>: Failed to resolve 'concourse-test.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://vap-coreuc-activation-proxy1.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='vap-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981390d0>, 'Connection to vap-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://vap-coreuc-activation-proxy1.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='vap-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598154c50>, 'Connection to vap-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://vap-coreuc-activation-proxy1.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='vap-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598157b30>, 'Connection to vap-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://argocd-loki-prod.fuze-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='argocd-loki-prod.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155dc0>, 'Connection to argocd-loki-prod.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://argocd-loki-prod.fuze-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='argocd-loki-prod.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155460>, 'Connection to argocd-loki-prod.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://argocd-loki-prod.fuze-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='argocd-loki-prod.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155820>, 'Connection to argocd-loki-prod.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://fuze-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981563f0>: Failed to resolve 'fuze-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://fuze-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138590>: Failed to resolve 'fuze-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://fuze-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139520>: Failed to resolve 'fuze-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://ansible-events.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='ansible-events.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139dc0>: Failed to resolve 'ansible-events.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://ansible-events.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='ansible-events.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981567b0>: Failed to resolve 'ansible-events.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://ansible-events.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='ansible-events.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156060>: Failed to resolve 'ansible-events.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://db.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='db.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155850>: Failed to resolve 'db.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='db.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155730>: Failed to resolve 'db.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='db.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156ba0>: Failed to resolve 'db.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.dep.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156e70>: Failed to resolve 'edge.dep.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.dep.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139ac0>: Failed to resolve 'edge.dep.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.dep.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981392b0>: Failed to resolve 'edge.dep.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.sgp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a540>: Failed to resolve 'edge.sgp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.sgp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813abd0>: Failed to resolve 'edge.sgp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.sgp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.sgp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b30>: Failed to resolve 'edge.sgp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://pif.fuze-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='pif.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598156ed0>, 'Connection to pif.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://pif.fuze-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='pif.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598154c20>, 'Connection to pif.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://pif.fuze-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='pif.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981575f0>, 'Connection to pif.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://csp.sec.s.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='csp.sec.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156b70>: Failed to resolve 'csp.sec.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.sec.s.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='csp.sec.s.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a600>: Failed to resolve 'csp.sec.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.sec.s.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='csp.sec.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139460>: Failed to resolve 'csp.sec.s.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://ipman.cloud.internal.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='ipman.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139c40>: Failed to resolve 'ipman.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://ipman.cloud.internal.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='ipman.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813af00>: Failed to resolve 'ipman.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://ipman.cloud.internal.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='ipman.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156420>: Failed to resolve 'ipman.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://aws-idp-okta-atlantis.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='aws-idp-okta-atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157ad0>: Failed to resolve 'aws-idp-okta-atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://aws-idp-okta-atlantis.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='aws-idp-okta-atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155610>: Failed to resolve 'aws-idp-okta-atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://aws-idp-okta-atlantis.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='aws-idp-okta-atlantis.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981571a0>: Failed to resolve 'aws-idp-okta-atlantis.mgmt.cloud.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://atlantis-aws-idp-okta.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='atlantis-aws-idp-okta.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981577a0>, 'Connection to atlantis-aws-idp-okta.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://atlantis-aws-idp-okta.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='atlantis-aws-idp-okta.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598139f40>, 'Connection to atlantis-aws-idp-okta.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://atlantis-aws-idp-okta.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='atlantis-aws-idp-okta.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813a240>, 'Connection to atlantis-aws-idp-okta.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139400>: Failed to resolve 'mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b0e0>: Failed to resolve 'mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b200>: Failed to resolve 'mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-dep.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157200>: Failed to resolve 'activation-dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-dep.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-dep.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981556a0>: Failed to resolve 'activation-dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-dep.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154c20>: Failed to resolve 'activation-dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.cas.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.cas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981557c0>: Failed to resolve 'edge.cas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cas.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.cas.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981575c0>: Failed to resolve 'edge.cas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cas.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.cas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b0e0>: Failed to resolve 'edge.cas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://ipfinder.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='ipfinder.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981394f0>, 'Connection to ipfinder.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://ipfinder.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='ipfinder.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981384a0>, 'Connection to ipfinder.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://ipfinder.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='ipfinder.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813b740>, 'Connection to ipfinder.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://db.m.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='db.m.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157320>: Failed to resolve 'db.m.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.m.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='db.m.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156fc0>: Failed to resolve 'db.m.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.m.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='db.m.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155760>: Failed to resolve 'db.m.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://border.vad.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='border.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154e00>: Failed to resolve 'border.vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.vad.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='border.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156720>: Failed to resolve 'border.vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.vad.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='border.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157050>: Failed to resolve 'border.vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://cnamaste.uc.p.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.p.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139700>: Failed to resolve 'cnamaste.uc.p.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.p.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.p.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981389e0>: Failed to resolve 'cnamaste.uc.p.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.p.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.p.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139670>: Failed to resolve 'cnamaste.uc.p.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.zap.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.zap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5983d4d10>: Failed to resolve 'edge.zap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.zap.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.zap.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981558e0>: Failed to resolve 'edge.zap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.zap.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.zap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981572c0>: Failed to resolve 'edge.zap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://sip.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='sip.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157f50>: Failed to resolve 'sip.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://sip.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='sip.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157740>: Failed to resolve 'sip.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://sip.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='sip.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156b40>: Failed to resolve 'sip.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-cas.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-cas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b00>: Failed to resolve 'activation-cas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cas.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-cas.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138ef0>: Failed to resolve 'activation-cas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cas.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-cas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a240>: Failed to resolve 'activation-cas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b140>: Failed to resolve 'edge.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156420>: Failed to resolve 'edge.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157320>: Failed to resolve 'edge.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://dep-coreuc-activation-proxy1.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='dep-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598157350>, 'Connection to dep-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://dep-coreuc-activation-proxy1.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='dep-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598156540>, 'Connection to dep-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://dep-coreuc-activation-proxy1.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='dep-coreuc-activation-proxy1.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981571a0>, 'Connection to dep-coreuc-activation-proxy1.uc.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://edge.hkp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.hkp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156ff0>: Failed to resolve 'edge.hkp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.hkp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.hkp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981399a0>: Failed to resolve 'edge.hkp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.hkp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.hkp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139a60>: Failed to resolve 'edge.hkp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://dps.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='dps.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a3f0>: Failed to resolve 'dps.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='dps.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a9c0>: Failed to resolve 'dps.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='dps.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155c40>: Failed to resolve 'dps.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156000>: Failed to resolve 'activation.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://activation.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157a40>: Failed to resolve 'activation.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://activation.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155ca0>: Failed to resolve 'activation.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://argo-infra8.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='argo-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157230>: Failed to resolve 'argo-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://argo-infra8.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='argo-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156420>: Failed to resolve 'argo-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://argo-infra8.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='argo-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a4b0>: Failed to resolve 'argo-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.aup.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.aup.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b8c0>: Failed to resolve 'edge.aup.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.aup.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.aup.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139340>: Failed to resolve 'edge.aup.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.aup.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.aup.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a480>: Failed to resolve 'edge.aup.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://stackstorm.m.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.m.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155730>: Failed to resolve 'stackstorm.m.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.m.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='stackstorm.m.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156db0>: Failed to resolve 'stackstorm.m.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.m.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.m.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981577d0>: Failed to resolve 'stackstorm.m.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://csp.sec.fuze.site?__proto__={"isHacked": true}
[+] Testing: https://csp.sec.fuze.site?constructor={"prototype": {"polluted": 1}}
[+] Testing: https://csp.sec.fuze.site?__proto__={"admin": true}
[-] No vulnerabilities detected.
[+] Testing: https://edge.vad.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157e90>: Failed to resolve 'edge.vad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vad.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155940>: Failed to resolve 'edge.vad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vad.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981558e0>: Failed to resolve 'edge.vad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://vam-cloudops-jenkins.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='vam-cloudops-jenkins.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813a4b0>, 'Connection to vam-cloudops-jenkins.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://vam-cloudops-jenkins.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='vam-cloudops-jenkins.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813a000>, 'Connection to vam-cloudops-jenkins.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://vam-cloudops-jenkins.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='vam-cloudops-jenkins.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813af60>, 'Connection to vam-cloudops-jenkins.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://cnamaste.uc.l.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.l.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155490>: Failed to resolve 'cnamaste.uc.l.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.l.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.l.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156450>: Failed to resolve 'cnamaste.uc.l.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.l.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.l.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156a80>: Failed to resolve 'cnamaste.uc.l.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://logs.internal.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='logs.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155730>: Failed to resolve 'logs.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://logs.internal.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='logs.internal.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981562a0>: Failed to resolve 'logs.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://logs.internal.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='logs.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157920>: Failed to resolve 'logs.internal.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-vap.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-vap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813ad80>: Failed to resolve 'activation-vap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vap.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-vap.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138e30>: Failed to resolve 'activation-vap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vap.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-vap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981390d0>: Failed to resolve 'activation-vap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://atlantis-test-elasticsearch.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='atlantis-test-elasticsearch.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598155be0>, 'Connection to atlantis-test-elasticsearch.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://atlantis-test-elasticsearch.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='atlantis-test-elasticsearch.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598157b90>, 'Connection to atlantis-test-elasticsearch.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://atlantis-test-elasticsearch.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='atlantis-test-elasticsearch.mgmt.cloud.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981571d0>, 'Connection to atlantis-test-elasticsearch.mgmt.cloud.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://atlantis-infra8.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='atlantis-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154c50>: Failed to resolve 'atlantis-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis-infra8.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='atlantis-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157080>: Failed to resolve 'atlantis-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://atlantis-infra8.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='atlantis-infra8.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156540>: Failed to resolve 'atlantis-infra8.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.cad.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.cad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139100>: Failed to resolve 'edge.cad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cad.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.cad.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813ab70>: Failed to resolve 'edge.cad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cad.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.cad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138320>: Failed to resolve 'edge.cad.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://cnamaste.uc.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5983d4d10>: Failed to resolve 'cnamaste.uc.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155eb0>: Failed to resolve 'cnamaste.uc.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981573b0>: Failed to resolve 'cnamaste.uc.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://db.s.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='db.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156ff0>: Failed to resolve 'db.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.s.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='db.s.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157560>: Failed to resolve 'db.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://db.s.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='db.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b00>: Failed to resolve 'db.s.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.vas.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.vas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981394c0>: Failed to resolve 'edge.vas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vas.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.vas.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981396d0>: Failed to resolve 'edge.vas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vas.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.vas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a990>: Failed to resolve 'edge.vas.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.cap.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.cap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139010>: Failed to resolve 'edge.cap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cap.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.cap.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155490>: Failed to resolve 'edge.cap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.cap.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.cap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156150>: Failed to resolve 'edge.cap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://csp.sec.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='csp.sec.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155700>: Failed to resolve 'csp.sec.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.sec.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='csp.sec.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156d20>: Failed to resolve 'csp.sec.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://csp.sec.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='csp.sec.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156270>: Failed to resolve 'csp.sec.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://cloudtest.mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cloudtest.mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59848b710>: Failed to resolve 'cloudtest.mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cloudtest.mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cloudtest.mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138b30>: Failed to resolve 'cloudtest.mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cloudtest.mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cloudtest.mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139040>: Failed to resolve 'cloudtest.mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-vbd.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813aa50>: Failed to resolve 'activation-vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://activation-vbd.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b6e0>: Failed to resolve 'activation-vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://activation-vbd.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-vbd.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155e20>: Failed to resolve 'activation-vbd.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://api-dev.mgmt.cloud.fuze.site?__proto__={"isHacked": true}
[+] Testing: https://api-dev.mgmt.cloud.fuze.site?constructor={"prototype": {"polluted": 1}}
[+] Testing: https://api-dev.mgmt.cloud.fuze.site?__proto__={"admin": true}
[-] No vulnerabilities detected.
[+] Testing: https://feedback.bk-os-dev.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='feedback.bk-os-dev.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155f10>: Failed to resolve 'feedback.bk-os-dev.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://feedback.bk-os-dev.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='feedback.bk-os-dev.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981554f0>: Failed to resolve 'feedback.bk-os-dev.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://feedback.bk-os-dev.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='feedback.bk-os-dev.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155520>: Failed to resolve 'feedback.bk-os-dev.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.brp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.brp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156150>: Failed to resolve 'edge.brp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.brp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.brp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b650>: Failed to resolve 'edge.brp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.brp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.brp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b410>: Failed to resolve 'edge.brp.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://stackstorm.s.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981390a0>: Failed to resolve 'stackstorm.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.s.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='stackstorm.s.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a750>: Failed to resolve 'stackstorm.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.s.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981572c0>: Failed to resolve 'stackstorm.s.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://dps.s.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='dps.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157740>: Failed to resolve 'dps.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.s.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='dps.s.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155ca0>: Failed to resolve 'dps.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.s.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='dps.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155e50>: Failed to resolve 'dps.s.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://border.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='border.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156600>: Failed to resolve 'border.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='border.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59837f4d0>: Failed to resolve 'border.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='border.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139ca0>: Failed to resolve 'border.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-cap.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-cap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813bc20>: Failed to resolve 'activation-cap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cap.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-cap.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155610>: Failed to resolve 'activation-cap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-cap.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-cap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981f82f0>: Failed to resolve 'activation-cap.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-vad.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138ec0>: Failed to resolve 'activation-vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vad.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-vad.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813b110>: Failed to resolve 'activation-vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vad.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-vad.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156c90>: Failed to resolve 'activation-vad.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://pvif.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='pvif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981577a0>: Failed to resolve 'pvif.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://pvif.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='pvif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981570e0>: Failed to resolve 'pvif.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://pvif.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='pvif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156c60>: Failed to resolve 'pvif.8x8-cloud-mgmt.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://pif.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='pif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155d90>: Failed to resolve 'pif.8x8-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://pif.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='pif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981f84d0>: Failed to resolve 'pif.8x8-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://pif.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='pif.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981f8830>: Failed to resolve 'pif.8x8-cloud-mgmt.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-val.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-val.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981573e0>: Failed to resolve 'activation-val.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-val.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-val.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156750>: Failed to resolve 'activation-val.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-val.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-val.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154d70>: Failed to resolve 'activation-val.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://cnamaste.uc.s.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155e50>: Failed to resolve 'cnamaste.uc.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.s.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.s.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157980>: Failed to resolve 'cnamaste.uc.s.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://cnamaste.uc.s.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cnamaste.uc.s.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154e30>: Failed to resolve 'cnamaste.uc.s.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://grafana-dev.fuze-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='grafana-dev.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981390a0>, 'Connection to grafana-dev.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://grafana-dev.fuze-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='grafana-dev.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb59813a630>, 'Connection to grafana-dev.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://grafana-dev.fuze-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='grafana-dev.fuze-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598139070>, 'Connection to grafana-dev.fuze-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://dns-tf.cloud.internal.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='dns-tf.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5983d4d10>: Failed to resolve 'dns-tf.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dns-tf.cloud.internal.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='dns-tf.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981571a0>: Failed to resolve 'dns-tf.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dns-tf.cloud.internal.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='dns-tf.cloud.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981579e0>: Failed to resolve 'dns-tf.cloud.internal.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-ukp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156d80>: Failed to resolve 'activation-ukp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-ukp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598154c80>: Failed to resolve 'activation-ukp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-ukp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-ukp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155cd0>: Failed to resolve 'activation-ukp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-vas.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-vas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598397590>: Failed to resolve 'activation-vas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vas.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-vas.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598139ca0>: Failed to resolve 'activation-vas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-vas.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-vas.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813bce0>: Failed to resolve 'activation-vas.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://api.rdns.internal.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='api.rdns.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a750>: Failed to resolve 'api.rdns.internal.fuze.site' ([Errno -3] Temporary failure in name resolution)"))
[+] Testing: https://api.rdns.internal.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='api.rdns.internal.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5991d6390>: Failed to resolve 'api.rdns.internal.fuze.site' ([Errno -3] Temporary failure in name resolution)"))
[+] Testing: https://api.rdns.internal.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='api.rdns.internal.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157b90>: Failed to resolve 'api.rdns.internal.fuze.site' ([Errno -3] Temporary failure in name resolution)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.aux.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.aux.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155940>: Failed to resolve 'edge.aux.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.aux.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.aux.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981566c0>: Failed to resolve 'edge.aux.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.aux.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.aux.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156630>: Failed to resolve 'edge.aux.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://border.dep.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='border.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155460>: Failed to resolve 'border.dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.dep.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='border.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157e90>: Failed to resolve 'border.dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://border.dep.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='border.dep.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813a750>: Failed to resolve 'border.dep.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-aup.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-aup.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981382f0>: Failed to resolve 'activation-aup.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-aup.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-aup.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981389b0>: Failed to resolve 'activation-aup.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-aup.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-aup.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598157860>: Failed to resolve 'activation-aup.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://activation-brp.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='activation-brp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156fc0>: Failed to resolve 'activation-brp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-brp.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='activation-brp.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156690>: Failed to resolve 'activation-brp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://activation-brp.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='activation-brp.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598155730>: Failed to resolve 'activation-brp.uc.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://edge.vap.uc.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='edge.vap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156c00>: Failed to resolve 'edge.vap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vap.uc.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='edge.vap.uc.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981565a0>: Failed to resolve 'edge.vap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[+] Testing: https://edge.vap.uc.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='edge.vap.uc.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981383b0>: Failed to resolve 'edge.vap.uc.fuze.site' ([Errno -5] No address associated with hostname)"))
[-] No vulnerabilities detected.
[+] Testing: https://stackstorm.d.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598138560>: Failed to resolve 'stackstorm.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.d.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='stackstorm.d.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb59813bb30>: Failed to resolve 'stackstorm.d.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://stackstorm.d.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='stackstorm.d.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981391f0>: Failed to resolve 'stackstorm.d.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.
[+] Testing: https://cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb5981573b0>, 'Connection to cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598156e40>, 'Connection to cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[+] Testing: https://cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7cb598156c30>, 'Connection to cloudmgmt-atlantis-aws-acs-ctrl.8x8-cloud-mgmt.fuze.site timed out. (connect timeout=10)'))
[-] No vulnerabilities detected.
[+] Testing: https://dps.p.fuze.site?__proto__={"isHacked": true}
[-] Error: HTTPSConnectionPool(host='dps.p.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22isHacked%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156240>: Failed to resolve 'dps.p.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.p.fuze.site?constructor={"prototype": {"polluted": 1}}
[-] Error: HTTPSConnectionPool(host='dps.p.fuze.site', port=443): Max retries exceeded with url: /?constructor=%7B%22prototype%22:%20%7B%22polluted%22:%201%7D%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb5981558b0>: Failed to resolve 'dps.p.fuze.site' ([Errno -2] Name or service not known)"))
[+] Testing: https://dps.p.fuze.site?__proto__={"admin": true}
[-] Error: HTTPSConnectionPool(host='dps.p.fuze.site', port=443): Max retries exceeded with url: /?__proto__=%7B%22admin%22:%20true%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7cb598156840>: Failed to resolve 'dps.p.fuze.site' ([Errno -2] Name or service not known)"))
[-] No vulnerabilities detected.